-- MySQL Script generated by MySQL Workbench
-- Sat Jun 10 13:37:41 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Work-Time-Tracker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Work-Time-Tracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Work-Time-Tracker` DEFAULT CHARACTER SET utf8 ;
USE `Work-Time-Tracker` ;

-- -----------------------------------------------------
-- Table `Work-Time-Tracker`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Work-Time-Tracker`.`user` (
  `idUser` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `access_control` TINYINT NULL,
  PRIMARY KEY (`idUser`));


-- -----------------------------------------------------
-- Table `Work-Time-Tracker`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Work-Time-Tracker`.`Employees` (
  `idEmployees` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmployees`),
  CONSTRAINT `fk_Employees_user1`
    FOREIGN KEY (`idEmployees`)
    REFERENCES `Work-Time-Tracker`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `Work-Time-Tracker`.`Tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Work-Time-Tracker`.`Tasks` (
  `idTasks` INT NOT NULL AUTO_INCREMENT,
  `task` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTasks`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `Work-Time-Tracker`.`Salary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Work-Time-Tracker`.`Salary` (
  `idSalary` INT NOT NULL AUTO_INCREMENT,
  `idEmployees` INT NOT NULL,
  `month` DATETIME NULL,
  `salary` DOUBLE NULL,
  PRIMARY KEY (`idSalary`),
  INDEX `fk_Salary_Employees1_idx` (`idEmployees` ASC),
  CONSTRAINT `fk_Salary_Employees1`
    FOREIGN KEY (`idEmployees`)
    REFERENCES `Work-Time-Tracker`.`Employees` (`idEmployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `Work-Time-Tracker`.`Employees_Tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Work-Time-Tracker`.`Employees_Tasks` (
  `idEmployees_Tasks` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idEmployees_Tasks`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `Work-Time-Tracker`.`Employees_has_Tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Work-Time-Tracker`.`Employees_has_Tasks` (
  `idEmployees_has_Tasks` INT NOT NULL AUTO_INCREMENT,
  `idEmployees` INT NOT NULL,
  `idTasks` INT NOT NULL,
  `rate_per_hour` DOUBLE NULL,
  `VAT` INT NULL,
  PRIMARY KEY (`idEmployees_has_Tasks`, `idEmployees`, `idTasks`),
  INDEX `fk_Employees_has_Tasks_Tasks1_idx` (`idTasks` ASC),
  INDEX `fk_Employees_has_Tasks_Employees_idx` (`idEmployees` ASC),
  CONSTRAINT `fk_Employees_has_Tasks_Employees`
    FOREIGN KEY (`idEmployees`)
    REFERENCES `Work-Time-Tracker`.`Employees` (`idEmployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employees_has_Tasks_Tasks1`
    FOREIGN KEY (`idTasks`)
    REFERENCES `Work-Time-Tracker`.`Tasks` (`idTasks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `Work-Time-Tracker`.`Logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Work-Time-Tracker`.`Logs` (
  `idLogs` INT NOT NULL AUTO_INCREMENT,
  `idEmployees_has_Tasks` INT NOT NULL,
  `start_time` DATETIME NULL,
  `stop_time` DATETIME NULL,
  `Logscol` VARCHAR(45) NULL,
  PRIMARY KEY (`idLogs`, `idEmployees_has_Tasks`),
  INDEX `fk_Logs_Employees_has_Tasks1_idx` (`idEmployees_has_Tasks` ASC),
  CONSTRAINT `fk_Logs_Employees_has_Tasks1`
    FOREIGN KEY (`idEmployees_has_Tasks`)
    REFERENCES `Work-Time-Tracker`.`Employees_has_Tasks` (`idEmployees_has_Tasks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Work-Time-Tracker`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `Work-Time-Tracker`;
INSERT INTO `Work-Time-Tracker`.`user` (`idUser`, `username`, `email`, `password`, `access_control`) VALUES (1, 'Pracodawca', 'p1@p.com', 'aaa', 1);
INSERT INTO `Work-Time-Tracker`.`user` (`idUser`, `username`, `email`, `password`, `access_control`) VALUES (2, 'Pracownik', 'e1@p.com', 'ppp', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Work-Time-Tracker`.`Employees`
-- -----------------------------------------------------
START TRANSACTION;
USE `Work-Time-Tracker`;
INSERT INTO `Work-Time-Tracker`.`Employees` (`idEmployees`, `name`, `lastname`, `position`) VALUES (1, 'Jan', 'Kowalski', 'director');
INSERT INTO `Work-Time-Tracker`.`Employees` (`idEmployees`, `name`, `lastname`, `position`) VALUES (2, 'Andrzej', 'Nowak', 'employee');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Work-Time-Tracker`.`Tasks`
-- -----------------------------------------------------
START TRANSACTION;
USE `Work-Time-Tracker`;
INSERT INTO `Work-Time-Tracker`.`Tasks` (`idTasks`, `task`) VALUES (1, 'Task1');

COMMIT;

